### ISSUE TITLE
无法阅览全文

### ISSUE THREAD

**Issue by TsingYX** [Naituw/WeiboX#1076]
微博内容很长时，点开后依旧不能看到全文。点开后在末尾（内容依旧是缩略的）会有全文的链接但是点击后没有反应。

![2018-10-14 10 39 00](https://user-images.githubusercontent.com/35586000/46927195-31ded800-d002-11e8-8687-aefb9caa90d4.png)
![2018-10-14 10 39 14](https://user-images.githubusercontent.com/35586000/46927196-32776e80-d002-11e8-97b7-79c01762a632.png)
![2018-10-14 10 39 24](https://user-images.githubusercontent.com/35586000/46927197-32776e80-d002-11e8-86b9-63446d2f6b51.png)

**Comment by bashang03** [comment]
有遇到类似问题，部分的微博点击“全文”按钮没反应
