### ISSUE TITLE
转发微博是发生，权限不够Insufficient app permissions! ( 错误代码:10014 )

### ISSUE THREAD

**Issue by AnkieEatApple** [Naituw/WeiboX#1121]
1. 在appstore上重新下载的maipo，并将账户已经获得高级授权，账户可以进行发微博，但是不能转发微博
2. 转发文字、图片、视频均出现10014错误

**Comment by AnkieEatApple** [comment]
1. 版本是3.5.0

**Comment by yusuuuuuu** [comment]
问题与 AnkieEatApple 相同，版本和情况也相同。昨天之前还能正常转发，从昨天开始转发时就一直出现10014错误了。

**Comment by AnkieEatApple** [comment]
1. 发现可以同过评论，同时转发微博的方式进行转发微博，直接转发不可以

**Comment by yusuuuuuu** [comment]
今天使用其他第三方微博app也无法转发了，提示的是微博API限制...估计微博对第三方app又加了什么限制...

**Comment by yuluo-ding** [comment]
好吧， 看来大家都遇到了，我以为是自己的问题呢。

**Comment by spademan** [comment]
+1

**Comment by alanban** [comment]
+1 持续半个月了  sina api的问题？
