### ISSUE TITLE
无法发微博 无法转发  发送信息时遇到错误

### ISSUE THREAD

**Issue by NathanDai** [Naituw/WeiboX#1122]
请求频次限制 
奈*-IFT:
Token: 2.00uMV52E0228gF867a027bdbmnUyp*
Superpower: 2.00uMV52Efj3PXC1421162dc8UmSIQ*
Scope: friendships_groups_read,friendships_groups_write,statuses_to_me_read
Create at: 2019/1/16 下午4:58
Expire in: 29 days

请求频次限制
奈*-IFT:
今日请求用量: 39985/40000
小时请求用量: 2000/2000

发送信息时遇到错误
Insufficient app permissions! ( 错误代码:10014 )

**Comment by spademan** [comment]
+1

**Comment by zhihuichan** [comment]
+1
