### ISSUE TITLE
[Feature]:Is it possible to login via the links of login?

### ISSUE THREAD

**Issue by MarcSteven** [Naituw/WeiboX#1137]
The latest version of Weibo   can only support to login via scanning the QR code but if you uninstalled the weibo client(iOS or Android),you cannot login in.It's not very convenient .So do you plan to add this features ?
Based on the weibo website [Weibo](https://weibo.com),there are three ways to login:
* 1, user account and password
* 2, Scan QR code to login
* 3,Mobile number 
But do you plan add other ways in the application to improve the user experiences ?Sorry to disturb your time ,but I truly love your product ,hope this feature is available later.

**Comment by Naituw** [comment]
You mean the QR code on the Weibo website login page right?

It’s actually the auth method implemented by official weibo.com, WeiboX
can’t control it

Marc Steven <notifications@github.com>于2019年3月1日 周五下午12:34写道：

**Comment by MarcSteven** [comment]
@Naituw  Thank for your reply ,I mean is it possible to add some other way to login  ...

**Comment by MarcSteven** [comment]
Long time no reply about this feature ,if the feature doesn't have public API ,I will close this issue.
As I know ,the website of Weibo  can support three types of login:
* 1,Account and Password, That's so normal ,most applications can support it 
* 2,Scan QRCode to login ,in this way you must install client for android or iOS ,or you cannot login 
* 3,SMS :You input your mobile number and then send SMS verify code and then accomplish the actions of login .
But now the  client for Mac only support "2" type ,that's why I opened this issue?Added more ways to login (Perhaps SMS or Account+Password ,you can choose anyone ,it can improve the users experiences in the following chapter because someone dislike to install client ,only review on the mac..I know perhaps time is limited ,but just my tips ,if any errors ,pls point out and pardon me...
Finally hope you own a happy day !!Thank for your sharing!!!

**Comment by MarcSteven** [comment]
Ok, because no reply ,perhaps it's not controllable  ,so close this issue.
