### ISSUE TITLE
登陆不了，试了好几种版本了，最新的也不行

### ISSUE THREAD

**Issue by WeiboX** [Naituw/WeiboX#119]
提交者：gmm94@qq.com

我是10.10.2的系统，在app store 下载  weibo for mac后，出现一个weiboX,打开后有一个“通过weibo.com登陆”点进去输入账号密码登录，自后weibo for mac出来,但是又弹出了一个授权mac客户端，一下就消失了，点都点不到，之后再点左边登陆，又会出现授权的弹窗，但很快就消失了，这。。。。登陆简直让我头疼

**Comment by Naituw** [comment]
用户使用的是旧版本的客户端
