### ISSUE TITLE
menubar小窗显示空白

### ISSUE THREAD

**Issue by lenppqq** [Naituw/WeiboX#12]
![dbf37f13-a2d8-480b-921f-cf6144dddcd4](https://cloud.githubusercontent.com/assets/6521392/4695639/e6a5b192-57d8-11e4-90ed-9a46e2231364.png)
MBP 13 OS X 10.10
点击之后会显示空白，关闭小窗之后再点击才显示正常内容。
重复上述两部会不断地在空白、正常内容之间切换。

**Comment by Naituw** [comment]
可以看下最新版本还有没有这个问题
