### ISSUE TITLE
Fix NSInvalidArgumentException in WMBlurView.m line 35

### ISSUE THREAD

**Issue by Naituw** [Naituw/WeiboX#1293]
### Stacktrace ###

main (main.m:30);Maipo

### Reason ###

NSInvalidArgumentException

### Link to App Center ###

* [https://appcenter.ms/users/naituw-bwtx/apps/Maipo/crashes/errors/2152239767u](https://appcenter.ms/users/naituw-bwtx/apps/Maipo/crashes/errors/2152239767u)

**Comment by yk4399** [comment]
<img width="631" alt="截屏2020-03-04上午9 26 49" src="https://user-images.githubusercontent.com/12847798/75839584-1c8b6900-5e04-11ea-8033-0654c076d006.png">
请问是这个错误吗？
