### ISSUE TITLE
Catalina 进行高级授权失败

### ISSUE THREAD

**Issue by hunterhl** [Naituw/WeiboX#1361]
我在MacOS Catalina 10.15.5版本上使用Maipo客户端，在使用客户端的私信功能时需要进行高级授权，但是在进行高级授权时提示未知错误，可以确定的是账号密码填写没有问题，请尽快更新

**Comment by hunterhl** [comment]
![image](https://user-images.githubusercontent.com/39644819/85496071-4a442a00-b60e-11ea-8b81-fa43563eaab0.png)
![image](https://user-images.githubusercontent.com/39644819/85496218-88d9e480-b60e-11ea-8f04-dd20cffee0cf.png)
以上是我的系统和客户端版本信息

**Comment by hunterhl** [comment]
图片好像不能显示：
系统:macOS Catalina 10.15.5
客户端:3.5.1（21664）

**Comment by Naituw** [comment]
最新版本已经修复
