### ISSUE TITLE
查看评论提示「Insufficient app permissions!」

### ISSUE THREAD

**Issue by raymondronaldo** [Naituw/WeiboX#1380]
昨天开始的。。。

**Comment by Naituw** [comment]
由于微博开放平台接口权限调整导致，修复版本已于上周末提交审核，目前遇到审核过慢的问题，准备今天先发布一个热修复补丁。

**Comment by raymondronaldo** [comment]
大神，新版还没审过吗？

**Comment by raymondronaldo** [comment]
> 由于微博开放平台接口权限调整导致，修复版本已于上周末提交审核，目前遇到审核过慢的问题，准备今天先发布一个热修复补丁。 From: raymondronaldo <notifications@github.com> Reply-To: Naituw/WeiboX <reply@reply.github.com> Date: Friday, July 17, 2020 at 2:19 PM To: Naituw/WeiboX <WeiboX@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Naituw/WeiboX] 查看评论提示「Insufficient app permissions!」 (#1380) 昨天开始的。。。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大神，新版还没过审吗？
