### ISSUE TITLE
提一个用户体验上面的问题

### ISSUE THREAD

**Issue by ulpyuxa** [Naituw/WeiboX#1535]
[https://drive.google.com/file/d/1v5FRWggA-FiRTM2ZgfYyQN4KbZHlgAUV/view?usp=sharing](url)
反馈个图片体验上面 的问题。如gif图中所示，如果左上角能固定位置应该就不会这这样的问题了。当然这也可以不是一个问题。

**Comment by Naituw** [comment]
这个是为了连续“下一张”特意设计的。

4.0 的图片查看器不会再变化窗口大小了，也不再存在这个问题
