### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by ChaosTong** [Naituw/WeiboX#1537]
触发条件, 几天没有关闭过软件, 然后中途经历过电脑休眠的情况下, 
出现打开视频, 缓存进度是在加载的, 但是无法正常播放,
关闭软件重新打开, 就能正常播放了. 可以稳定的复现, 问题存在有一段时间了

version: 3.5.3 build: 22580, 系统版本 10.15.7

**Comment by Naituw** [comment]
目前最新版本是 3.5.5，可以更新一下看问题是否还存在

**Comment by ChaosTong** [comment]
4.0.0 用了几天了, 好想是没有再出现了, 暂时先 close 了
