### ISSUE TITLE
无法高级授权

### ISSUE THREAD

**Issue by dowhilenet** [Naituw/WeiboX#158]
如图
![qq20150324-2 2x](https://cloud.githubusercontent.com/assets/10379476/6816310/740fc888-d2cc-11e4-9bf1-b94404ae7443.png)

**Comment by leecade** [comment]
:+1:

**Comment by sosia** [comment]
> Me too!

**Comment by Naituw** [comment]
请在系统自带的“终端.app”中执行以下命令，然后重启 WeiboX，应该就可以了！ 
`rm -f ~/Library/Containers/com.wutian.weibo/Data/Library/Caches/com.wutian.weibo/Cache.db`
