### ISSUE TITLE
用户主页微博信息为空

### ISSUE THREAD

**Issue by chenjc0317** [Naituw/WeiboX#1623]
我已录制视频放在附件中
Maipo版本：4.0.0（23547）
macOS版本：macOS Big Sur 11.1

https://user-images.githubusercontent.com/47734570/103859427-fa820780-50f4-11eb-8f2f-dff63b726239.mp4

**Comment by ajsonx** [comment]
+1 
Maipo: 4.0.0(23547)
System: 版本 10.13.6（版号 17G65）

**Comment by Murmanskz** [comment]
+1  出现问题后我退出登录了，然后就再也登不上了

**Comment by yangxiv** [comment]
+1 Maipo：4.0.0（23547）

**Comment by yangxiv** [comment]
系统：版本11.1(20C69)

**Comment by yangxiv** [comment]
+1 macos Big Sur
版本111(20C69)
Maipo：4.0.0（23547）

**Comment by ugaxm** [comment]
+1 
Maipo：4.0.0（23547）
macos Big Sur 11.1

**Comment by jonnyRain** [comment]
+1
Maipo：4.0.0（23547）
macos Big Sur 11.1
![image](https://user-images.githubusercontent.com/1166916/104143173-63b99180-53f9-11eb-9dd4-70ab3330c58b.png)
点击信息为空用户首页 再点击空白区域后 会出现截图中的内容
