### ISSUE TITLE
微博无法刷新User requests out of rate limit!

### ISSUE THREAD

**Issue by HelloGeekMan** [Naituw/WeiboX#165]
微博无法刷新，关闭WeiboX重启后，Timeline无内容，显示User requests out of rate limit!

合上屏幕一段时间，再重新开启时，发生此种情况，且合上之前有连接vpn。

**Comment by ernestyao** [comment]
一样问题，如果取消账号授权重新绑定账号，也会有此提示，无法授权账号了

**Comment by sinnyn** [comment]
应该是微博平台机制更新的原因，可能需要作者更改API的访问频次。参见http://weibo.com/p/1001603805813964723833

**Comment by liuhy1991** [comment]
嗯，最好能在preference里能让用户自行设置访问频次。
