### ISSUE TITLE
我来给图片查看提个建议

### ISSUE THREAD

**Issue by free1978** [Naituw/WeiboX#21]
目前的图片还是在timeline中带个小图，我希望能直接用大图在timeline中。比如一个微博带了9张大图，每张都**全宽度顺序显示**。这样我只需要上下滚动timeline就行，也不需要点开，也不需要再双击关闭。
如果能加上**自动滚动**，那就更好了。

**Comment by Naituw** [comment]
现在的悬浮预览功能应该算是折中解决了这个问题
