### ISSUE TITLE
登录失败问题

### ISSUE THREAD

**Issue by YokioeXie** [Naituw/WeiboX#2209]
![截屏2023-03-28 18 57 11](https://user-images.githubusercontent.com/86205765/228216298-ae568d96-95cd-4c2c-8f99-0aaa6cbe26c2.png)

开发者你好，这个应该怎么办？

**Comment by Naituw** [comment]
这个一般是由于出问题之前接口调用太频繁了，被服务端限制了，正常过几个小时会恢复。
如果觉得自己没有过于频繁的操作，下次遇到时可以尝试回忆一下出现之前使用过什么功能，反馈给我我排查一下。
