### ISSUE TITLE
Fix crash in _dispatch_queue_wakeup_with_qos_slow

### ISSUE THREAD

**Issue by Naituw** [Naituw/WeiboX#292]
### Reason

No reason found. Full stack trace includes libdispatch.dylib, libsystem_network.dylib, CFNetwork, CoreFoundation, Foundation, libsystem_pthread.dylib.
### Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/114711/crash_reasons/41806053](https://rink.hockeyapp.net/manage/apps/114711/crash_reasons/41806053)

**Comment by chamberlin-dev** [comment]
I've been having a similar problem in my project. As of yet, no clue what's happening. Please post solution if you find one, and perhaps it will be applicable (and I shall do the same here, if I figure out mine).

Good luck.

**Comment by brototyp** [comment]
I recently found this in one of our Apps and stumbled upon this thread in the Apple Forums: https://forums.developer.apple.com/thread/15702

This might be an iOS 9 Beta only issue. We've only seen it in iOS 9 Beta versions.
