### ISSUE TITLE
Security problem in old version (2.8.0)

### ISSUE THREAD

**Issue by steven1227** [Naituw/WeiboX#441]
微博长期使用者. 之前在个人电脑上使用 网页端, mac客户端, 还有ios, Android 都没问题. 最近在公司Mac上由于APP store的一些问题, 我直接下载了官网上的旧版本2.8.0 使用. 结果不出一天微博就被盗取了.... 我很肯定是这个旧版本中的一些问题. 希望能给予重视.

**Comment by Naituw** [comment]
如果是在旧版本使用高级授权，会使用开放平台旧版的 OAuth 2.0 Client Auth 方式，通过 HTTPS 发送用户名密码到微博的服务器校验。如果你所在的网络环境受到中间人攻击，并且你也在电脑上信任了相关证书，可能导致密码被泄漏。

这个是旧版本使用的授权机制的问题导致，我这边可能会在将来撤下官网的旧版下载入口

**Comment by steven1227** [comment]
@Naituw 可能是。我使用了旧版本私信功能并且授权了。感谢回复。
