### ISSUE TITLE
全屏模式下的图片浏览问题

### ISSUE THREAD

**Issue by alterall** [Naituw/WeiboX#578]
希望全屏模式下能依旧和3.1.2一样弹出小窗口而不是新开全屏窗口，用弹出窗口看图片方便很多。

**Comment by iVoldemort** [comment]
同意。打开全屏窗口无法展示图片全貌，必须切换一下图片才行，如果是单幅图片的就没法看到全貌。多图的点开图片无法用鼠标操作，只能用键盘切换图片一次之后，才能用鼠标操作
