### ISSUE TITLE
賬號洩露哦

### ISSUE THREAD

**Issue by liubiao0810** [Naituw/WeiboX#590]
剛剛下載了一個試了下，居然可以看到某個人的賬號，然而密碼是網頁版的，輕輕鬆鬆就看到了，應該是混寸的問題，提BUG了哈；

**Comment by liubiao0810** [comment]
jundream1988@sina.com
ku*n*liu******
這就是抓取到的，這bug足矣搞死自己啊！！！

**Comment by Naituw** [comment]
什么意思。。不懂

**Comment by liubiao0810** [comment]
稍等我給你截圖

**Comment by liubiao0810** [comment]
就是可以看到別人的賬號和密碼

**Comment by Naituw** [comment]
怎么看

**Comment by liubiao0810** [comment]
上傳不了啊。怎麼發你？就是別人的賬號看見了，有事再瀏覽器打開登陸的，那麼密碼也就可以輕鬆看到了

**Comment by liubiao0810** [comment]
![54548504-0264-4cd8-82ab-85011e4d8aac](https://cloud.githubusercontent.com/assets/11221788/21303842/488e4728-c5fc-11e6-8cf4-89d780f0dd7d.png)

**Comment by liubiao0810** [comment]
圖片已上傳自己看吧

**Comment by Naituw** [comment]
这是你的浏览器存的密码吧

**Comment by liubiao0810** [comment]
![wx20161219-150433](https://cloud.githubusercontent.com/assets/11221788/21303876/7b0b58bc-c5fc-11e6-9c23-842638e8bd08.png)
這個賬號我都不知道是誰

**Comment by liubiao0810** [comment]
哎~~隨便信不信吧，好心提bug，不信算了

**Comment by Naituw** [comment]
麻烦你把发的微博删了，这个问题跟 WeiboX 没关系，账号密码是你自己 Safari 浏览器记录的

**Comment by liubiao0810** [comment]
哎~~~
