### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by WeiboX** [Naituw/WeiboX#60]
提交者：@HYY_369 email:yysh96@gmail.com

微博api完成授权后不自动跳转回app，完成授权后app完全没有反应。
在美国登录的，没有使用代理。
OS X 10.10.1 MacBook Pro (Retina, 13-inch, Mid 2014)
WeiboX V3.0 download from App Store

**Comment by Naituw** [comment]
统一关闭早期的 Issue，如果仍有问题，欢迎重开
