### ISSUE TITLE
快捷键

### ISSUE THREAD

**Issue by insurgo222** [Naituw/WeiboX#89]
不能使用「L」来查看详细微博，也不能用「H」来返回

**Comment by ooopscc** [comment]
+1 
如果可以自己定义快捷键就更好了
另外trackpad的手势也希望可以自己定义，因为有的确实不太习惯

**Comment by Naituw** [comment]
将在后续版本改进

**Comment by Naituw** [comment]
统一关闭早期的 Issue，如果仍有问题，欢迎重开
